version: '3.8'

services:
  credit-card-service:
    image: ssamantr/credit-card:0.0.1-SNAPSHOT
    ports:
      - "9000:9000"
    restart: always
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 500M
    networks:
      - spring-microservices-kubed-network

  customer-loan-service:
    image: ssamantr/customer-loan:0.0.1-SNAPSHOT
    ports:
      - "8090:8090"
    restart: always
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 500M
    networks:
      - spring-microservices-kubed-network

  user-account-service:
    image: ssamantr/user-account:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    restart: always
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 500M
    networks:
      - spring-microservices-kubed-network

networks:
  spring-microservices-kubed-network: