server:
  port: 8080

spring:
  application:
    name: accounts
  config:
    import: optional:configserver:http://localhost:8071
  profiles:
    active: prod
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: rabbit
    rabbitmq:
      queue: zipkin
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/

resilience4j:
  circuitbreaker:
    instances:
      customer-details:
        registerHealthIndicator: true
        minimumNumberOfCalls: 6
        failureRateThreshold: 50
        waitDurationInOpenState: 3s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: TIME_BASED
        eventConsumerBufferSize: 10
  retry:
    instances:
      customer-details:
        maxAttempts: 3
        waitDuration: 5s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
  ratelimiter:
    instances:
      customer-details:
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 5s
