INSERT INTO CUSTOMER_TABLE (CUSTOMER_NAME, CUSTOMER_EMAIL, MOBILE_NUMBER, CREATION_DATE)
 VALUES ('Rosa Sanchez','rosa2603@gmail.com','9876548337',CURDATE());
 
INSERT INTO ACCOUNTS_TABLE (CUSTOMER_ID, ACCOUNT_TYPE, BRANCH_ADDRESS, CREATE_DATE)
 VALUES (186576453,'Savings','123 Main Street, Culliacan',CURDATE());
 
