apiVersion: apps/v1
kind: Deployment
metadata:
  name: discoveryserver-deployment
  labels:
    app: discoveryserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discoveryserver
  template:
    metadata:
      labels:
        app: discoveryserver
    spec:
      containers:
        - name: discoveryserver
          image: ssamantr/discovery-server:latest
          ports:
            - containerPort: 8070
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: spring-microservice-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_ZIPKIN_BASEURL
              valueFrom:
                configMapKeyRef:
                  name: spring-microservice-configmap
                  key: SPRING_ZIPKIN_BASEURL

---
apiVersion: v1
kind: Service
metadata:
  name: discoveryserver-service
spec:
  selector:
    app: discoveryserver
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8070
      targetPort: 8070
