server:
  port: 8070

eureka:
  instance.hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: discovery-server
  cloud:
    config:
      enabled: false
    loadbalancer:
      ribbon.enabled: false
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: rabbit
    rabbitmq:
      queue: zipkin
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
