server:
  port: 8090

spring:
  application:
    name: loans
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: rabbit
    rabbitmq:
      queue: zipkin
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/

loans:
  msg: Welcome to Loans default application
  build-version: 3
  mailDetails:
    hostName: default-loans@gmail.com
    port: 9002
    from: default-loans@gmail.com
    subject: Your Loan Details from Default Environment
  activeBranches: [Mumbai, London, Washington]