server:
  port: 8071

spring:
  application:
    name: configserver
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config

#server:
#  port: 8071
#
#spring:
#  application:
#    name: configserver
#  profiles:
#    active: git
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/ssamparn/config-repo.git
#          username: ssamparn
#          password: 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
#          default-label: master
#          clone-on-start: true

