server:
  port: 8071

spring:
  application:
    name: configserver
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ssamparn/config-repo.git
          username: ssamparn
          password: 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
          default-label: master
          clone-on-start: true