accounts:
  msg: '{cipher}5e3ef52c2f0bc7db2c2ca5135ca7d42f40e93f9c7463807b6da1d0a7bcfe5164f6d8d96dcb6ed700de5e2d1490232992f999dd56c013a16ecc2708ec03bbf323'
  build-version: 2
  mailDetails:
    hostName: prod-accounts@gmail.com
    port: 9010
    from: prod-accounts@gmail.com
    subject: Your Account Details from Prod Environment
  activeBranches: [Hyderabad, Paris, NewYork]