cards:
  msg: Welcome to Cards default application
  build-version: 3
  mailDetails:
    hostName: default-cards@gmail.com
    port: 9002
    from: default-cards@gmail.com
    subject: Your Card Details from Default Environment
  activeBranches: [Mumbai, London, Washington]